language: php
sudo: false

php:
        - 5.6
        - 7.0

script:
        - cd src && (php -dshort_open_tag=On test.php -v --baseline) && (php -dshort_open_tag=On test.php -v --deployed --baseline);
